function create_scatterhist(data1, data2, X1, Y1, figure_handle, meth, stim, coh, save_flag)
% _
% Function to create the figure of a scatterplot with histograms on each
% axis
% 
% function CREATEFIGURE(DATA1, DATA2, X1, Y1)
% IN:
%     DATA1:  histogram data
%     DATA2:  histogram data
%     X1:  vector of x data
%     Y1:  vector of y data
%     figure_handle: Handle of the figure where the data will be plotted in
%     meth: define response method, either "bar" or "trackball
%     stim: define either of the three stimuli, transparent motion, brownian
%     motion, white noise motion
%     coh: define the coherence level, 0%, 12.5%, 25%, 50%, 100%
% 
% Auto-generated by MATLAB on 02-Dec-2019 17:58:22
% edited by Felix Töpfer <felix.toepfer@bccn-berlin.de>, 31/03/2020
% edited by Felix Töpfer <felix.toepfer@bccn-berlin.de>, 19/07/2022


% set header and axis
head_str = sprintf('%s: %s%% coherence', stim, coh);

axes1 = axes('Parent',figure_handle,...
    'Position',[0.06 0.30 0.217016129032258 0.55],...
    'Tag','yhist');
axis off


% Create histogram
histogram(data2,'DisplayName','x','Parent',axes1,'FaceColor',[0 0 0],...
    'BinWidth',12);

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[0 360]);
 xticks(axes1,[])
 ylim(axes1, [0 200]);
 yticks([0,200])
 
 set(axes1,'FontSize',30,'FontWeight','bold')

view(axes1,[270 90]);
box(axes1,'on');

% Create axes
axes2 = axes('Parent',figure_handle,...
    'Position',[0.465 0.02 0.44 0.10886518687685],...
    'Tag','xhist');
axis off

% Create histogram
histogram(data1,'DisplayName','x','Parent',axes2,'FaceColor',[0 0 0],...
    'BinWidth',12);


% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes2,[0 360]);
 xticks(axes2,[])
 ylim(axes2,[0 55]);
 set(axes2,'FontSize',30,'FontWeight','bold', 'FontName', 'Times')

% Uncomment the following line to preserve the Y-limits of the axes
box(axes2,'on');
axis(axes2,'ij');

% Create axes
axes3 = axes('Parent',figure_handle,'Position',[0 1 1 1],'Tag','suptitle');
axis off

%Create text
text('Parent',axes3,'HorizontalAlignment','center','FontWeight','bold',...
    'FontSize',30,...
    'String',{head_str},...
    'Position',[0.5 -0.05 0],...
    'Visible','on');


% Create axes
axes4 = axes('Parent',figure_handle,...
    'Position',[0.41 0.30 0.55 0.55],...
    'Tag','scatter');
hold(axes4,'on');

% Create plot
plot(X1,Y1,'Parent',axes4,'Marker','.','LineStyle','none','Color',[0 0 0],'MarkerSize',10);

hold on,
plot([0:360],[0:360],'-','Color',[1 0 0],'LineWidth',2);

% Create xlabel
xlabel('presented [°]','FontWeight','bold','FontSize',30);

% Create ylabel
ylabel('reported [°]','FontWeight','bold','FontSize',30);

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes4,[0 360]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes4,[0 360]);
box(axes4,'on');
% Set the remaining axes properties
set(axes4,'FontSize',30,'FontWeight','bold','PlotBoxAspectRatio',...
    [180 180 1],'XTick',[0 180 360],'YTick',[0 180 360],...
    'LineWidth', [2]);

            
    if save_flag==1
        save_folder=pwd;              
        save_name=[meth ' ' 'scatter_plot'  ' ' stim ' ' coh '.pdf'];
        saveas(gcf,fullfile(save_folder,save_name))
    end
end